declare module 'lucide-react' {
  import { FC, SVGProps } from 'react';
  
  export interface IconProps extends SVGProps<SVGSVGElement> {
    size?: string | number;
    strokeWidth?: string | number;
    absoluteStrokeWidth?: boolean;
  }
  
  export type LucideIcon = FC<IconProps>;
  
  // Comprehensive list of all icons used in the project
  export const Mail: LucideIcon;
  export const Lock: LucideIcon;
  export const ArrowLeft: LucideIcon;
  export const ArrowRight: LucideIcon;
  export const Shield: LucideIcon;
  export const KeyRound: LucideIcon;
  export const Loader2: LucideIcon;
  export const Calendar: LucideIcon;
  export const Download: LucideIcon;
  export const Trash2: LucideIcon;
  export const Eye: LucideIcon;
  export const FileText: LucideIcon;
  export const Search: LucideIcon;
  export const Filter: LucideIcon;
  export const ChevronLeft: LucideIcon;
  export const ChevronRight: LucideIcon;
  export const Upload: LucideIcon;
  export const Plus: LucideIcon;
  export const X: LucideIcon;
  export const Edit3: LucideIcon;
  export const Copy: LucideIcon;
  export const Users: LucideIcon;
  export const Clock: LucideIcon;
  export const CheckCircle: LucideIcon;
  export const CheckCircle2: LucideIcon;
  export const AlertCircle: LucideIcon;
  export const Bell: LucideIcon;
  export const Settings: LucideIcon;
  export const Sparkles: LucideIcon;
  export const Layers: LucideIcon;
  export const Settings2: LucideIcon;
  export const Play: LucideIcon;
  export const PlayCircle: LucideIcon;
  export const Save: LucideIcon;
  export const Send: LucideIcon;
  export const MessageCircle: LucideIcon;
  export const BookOpen: LucideIcon;
  export const Edit: LucideIcon;
  export const MapPin: LucideIcon;
  export const UserCheck: LucideIcon;
  export const XCircle: LucideIcon;
  export const PlusCircle: LucideIcon;
  export const UploadCloud: LucideIcon;
  export const CheckIcon: LucideIcon;
  export const ChevronDownIcon: LucideIcon;
  export const ChevronUpIcon: LucideIcon;
  export const CircleIcon: LucideIcon;
  export const ChevronRightIcon: LucideIcon;
  export const XIcon: LucideIcon;
  export const EyeOff: LucideIcon;
  export const User: LucideIcon;
  export const RotateCcw: LucideIcon;
  export const RefreshCw: LucideIcon;
  export const HelpCircle: LucideIcon;
  export const Leaf: LucideIcon;
  export const FileEdit: LucideIcon;
  export const FilePenLine: LucideIcon;
  export const Award: LucideIcon;
  export const Check: LucideIcon;
  export const FileCheck: LucideIcon;
  export const Brain: LucideIcon;
  export const Cloud: LucideIcon;
  export const Compass: LucideIcon;
  export const Globe: LucideIcon;
  export const GraduationCap: LucideIcon;
  export const Heart: LucideIcon;
  export const LineChart: LucideIcon;
  export const MessageSquare: LucideIcon;
  export const MonitorSmartphone: LucideIcon;
  export const PieChart: LucideIcon;
  export const Target: LucideIcon;
  export const Trophy: LucideIcon;
  export const Zap: LucideIcon;
  export const Flame: LucideIcon;
  export const TrendingUp: LucideIcon;
  export const TrendingDown: LucideIcon;
  export const LayoutGrid: LucideIcon;
  export const Home: LucideIcon;
  export const LogOut: LucideIcon;
  export const Menu: LucideIcon;
  export const CircleUser: LucideIcon;
  export const Moon: LucideIcon;
  export const Sun: LucideIcon;
  export const BarChart3: LucideIcon;
  export const ChevronDown: LucideIcon;
  export const Delete: LucideIcon;
  export const Trash: LucideIcon;
  export const Timer: LucideIcon;
  export const BarChart2: LucideIcon;
  export const Clock3: LucideIcon;
}
